export const CLIENT_PREDICTION_TICK_RATE = 60;
export const CLIENT_PREDICTION_FIXED_DELTA_SECONDS = 1 / CLIENT_PREDICTION_TICK_RATE;
export const MAX_PREDICTION_CATCH_UP_STEPS = 8;
export const MAX_PENDING_INPUTS = 256;
export const MAX_PREDICTION_TICK_HISTORY = 512;
export const MAX_PREDICTION_REPLAY_TICKS = 30;
export const MAX_PREDICTION_PROXY_LEAD_TICKS = 12;

export const PREDICTION_SMALL_ERROR_METERS = 0.15;
export const PREDICTION_HARD_SNAP_METERS = 5;
export const PREDICTION_VISUAL_DEAD_ZONE_METERS = 0.04;
export const PREDICTION_VISUAL_DEAD_ZONE_DEGREES = 0.75;
export const PREDICTION_CORRECTION_EVENT_METERS = PREDICTION_VISUAL_DEAD_ZONE_METERS;
export const PREDICTION_CORRECTION_EVENT_DEGREES = PREDICTION_VISUAL_DEAD_ZONE_DEGREES;
export const PREDICTION_SMALL_CORRECTION_RATE = 8;
export const PREDICTION_MEDIUM_CORRECTION_RATE = 16;

// Rapier applies the configured engine force independently to both driven
// rear wheels. The lightweight visual predictor must use the combined force;
// this does not change authoritative vehicle tuning.
export const PREDICTION_DRIVEN_WHEEL_COUNT = 2;

export const REMOTE_EXTRAPOLATION_MAX_MS = 150;
export const REMOTE_EXTRAPOLATION_MAX_TICKS =
  (CLIENT_PREDICTION_TICK_RATE * REMOTE_EXTRAPOLATION_MAX_MS) / 1_000;
export const INTERPOLATION_BASE_DELAY_MS = 100;
export const INTERPOLATION_MAX_DELAY_MS = 150;
export const INTERPOLATION_JITTER_MULTIPLIER = 2;
