export const SIMULATION_TICK_RATE = 60;
export const SIMULATION_FIXED_DELTA_SECONDS = 1 / SIMULATION_TICK_RATE;

export const NETWORK_UPDATE_RATE = 10;
export const TICKS_PER_NETWORK_UPDATE = SIMULATION_TICK_RATE / NETWORK_UPDATE_RATE;

export const SNAPSHOT_RATE = 20;
export const TICKS_PER_SNAPSHOT = SIMULATION_TICK_RATE / SNAPSHOT_RATE;
export const SNAPSHOT_INTERPOLATION_DELAY_MS = 100;
export const SNAPSHOT_INTERPOLATION_DELAY_TICKS =
  (SIMULATION_TICK_RATE * SNAPSHOT_INTERPOLATION_DELAY_MS) / 1_000;

export const INPUT_SEND_RATE = 30;
export const INPUT_SEND_INTERVAL_MS = 1_000 / INPUT_SEND_RATE;

export const MAX_PLAYERS_PER_ROOM = 8;
export const ROOM_ID_LENGTH = 6;
export const MIN_PLAYER_NAME_LENGTH = 1;
export const MAX_PLAYER_NAME_LENGTH = 16;
export const PING_INTERVAL_MS = 2_000;
