export const COLLISION_MEMBERSHIP = {
  WORLD: 0x0001,
  PLAYER_VEHICLE: 0x0002,
  CONVOY: 0x0004,
  GAMEPLAY_TRIGGER: 0x0008,
} as const;

function interactionGroups(membership: number, filter: number): number {
  return ((membership & 0xffff) << 16) | (filter & 0xffff);
}

export const WORLD_COLLISION_GROUPS = interactionGroups(
  COLLISION_MEMBERSHIP.WORLD,
  COLLISION_MEMBERSHIP.PLAYER_VEHICLE,
);

export const PLAYER_COLLISION_GROUPS = interactionGroups(
  COLLISION_MEMBERSHIP.PLAYER_VEHICLE,
  COLLISION_MEMBERSHIP.WORLD |
    COLLISION_MEMBERSHIP.PLAYER_VEHICLE |
    COLLISION_MEMBERSHIP.CONVOY,
);

export const CONVOY_COLLISION_GROUPS = interactionGroups(
  COLLISION_MEMBERSHIP.CONVOY,
  COLLISION_MEMBERSHIP.PLAYER_VEHICLE,
);

export const VEHICLE_SUPPORT_QUERY_GROUPS = interactionGroups(
  COLLISION_MEMBERSHIP.PLAYER_VEHICLE,
  COLLISION_MEMBERSHIP.WORLD | COLLISION_MEMBERSHIP.CONVOY,
);
